owner: chse-ci
repo: upptime
user-agent: github.com/chse-ci/upptime

sites:
  - name: Main Server
    url: https://chse.dev
  - name: Backup Server
    check: "tcp-ping"
    url: offsite-backup.chse.dev
    port: 22
  - name: MKW Server
    check: "tcp-ping"
    url: mkw.chse.dev
    port: 22

assignees:
  - chse-ci

status-website:
  cname: uptime.chse.dev
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Uptime
  theme: night
  css: "footer { display: none } body,nav,article { background: black }"
  metaTags:
    - name: "robots"
      content: "noindex"

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
